kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64
steps:
  - name: test
    image: ruby:2.6
    commands:
      - gem install bundler -v 2.0.2
      - bundle install --path bundler
      - bundle exec rspec spec/
      - bundle exec rubocop lib/
  - name: docker_latest
    image: plugins/docker
    settings:
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quay.io/kontena/mortar
      dockerfile: Dockerfile
      auto_tag: true
    when:
      branch: ['master']
      event: ['push']
  - name: docker_release
    image: plugins/docker
    settings:
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quay.io/kontena/mortar
      dockerfile: Dockerfile
      auto_tag: true
    when:
      event: ['tag']
  - name: release-gem
    image: ruby:2.4
    environment:
      RUBYGEMS_AUTH:
        from_secret: rubygems_auth
    commands:
      - mkdir -p ~/.gem
      - echo $RUBYGEMS_AUTH | base64 -d > ~/.gem/credentials && chmod 0600 ~/.gem/credentials
      - gem build kontena-mortar.gemspec
      - gem push *.gem
    when:
      event: ['tag']
  - name: create_gh_release
    image: ubuntu:xenial
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - ./build/drone/create_release.sh
    when:
      event: tag
  - name: build_xenial
    image: ubuntu:xenial
    environment:
      CPPFLAGS: '-P'
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - ./build/drone/ubuntu_xenial.sh
    when:
      event: tag
